### ISSUE TITLE
Repo and feature rename

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-quote#3]
We've been talking about this in https://github.com/ckeditor/ckeditor5/issues/393 and I'm very confused.

As far as I understand, this repository is the implementation of the "Message Quote" feature. Instead, it has been named like the "Quote" feature.

What about deciding for the final name and rename it? I've suggested already "Message Quote", "Reply Quote" and "In-Reply Quote". I'm fine with any one of them.

**Comment by Reinmar** [comment]
The repo is called ckeditor5-quote because it was supposed to contain both features. Just like lists and basic styles and image also contain multiple plugins. So, I hope that this is fine. If we consider those two quote features that unconnectedm, then we can rename the repo to match feature name.

Regarding feature name – I started with Message Quote, but I wanted to rename it after our recent discussions. Reply Quote is nice because it's short. I was also googling to check if In-Reply Quote is ok, but I haven't clearly confirmed that.

Can we check with some other guys which name fits the best?

**Comment by Reinmar** [comment]
> Can we check with some other guys which name fits the best?

I meant – some of them may not be intuitive.

**Comment by fredck** [comment]
> The repo is called ckeditor5-quote because it was supposed to contain both features. Just like lists and basic styles and image also contain multiple plugins. So, I hope that this is fine. If we consider those two quote features that unconnectedm, then we can rename the repo to match feature name.

Ah, ok. Still I would go with separate repos, because these are different features and I believe that people will use either one or the other.

**Comment by Reinmar** [comment]
OK, then `ckeditor5-message-quote` and `MessageQuote` feature.

And yes, I've got a problem with the fact that feature name must be `CamelCase`, but the package name describes a feature not a plugin per se, so it's `message-quote`. But naming the package `ckeditor5-messagequote` will bring the same confusion when it's listed next to `ckeditor5-basic-styles` (which has multiple plugins inside, none called `BasicStyles`).
